# Generated by Django 5.0.6 on 2024-06-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('fullName', models.CharField(max_length=30)),
                ('salt', models.CharField(max_length=50)),
                ('hashedPassword', models.CharField(max_length=128)),
                ('contactInfo', models.CharField(max_length=60)),
                ('dateOfBirth', models.CharField(max_length=9)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
