# Generated by Django 5.0.6 on 2024-06-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contactInfo',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
