# Generated by Django 5.0.6 on 2024-09-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_user_isprivate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accountBasedIn',
            field=models.CharField(default='', max_length=320),
        ),
        migrations.AlterField(
            model_name='user',
            name='contactInfo',
            field=models.CharField(max_length=320),
        ),
    ]
