apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: login-register-frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: login-register-frontend-deployment
  minReplicas: 1
  maxReplicas: 7
  targetCPUUtilizationPercentage: 70