apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-register-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-register-backend
  template:
    metadata:
      labels:
        app: login-register-backend
    spec:
      containers:
      - name: login-register-backend-container
        image: rishavry/login-register-backend:v4
        ports:
        - containerPort: 8001
        envFrom:
        - secretRef:
            name: login-register-backend-env-secrets
        volumeMounts:
        - name: google-credentials-json-secret-volume
          mountPath: /app/megagram-428802-d974cd9b0ed9.json
          subPath: megagram-428802-d974cd9b0ed9.json
          readOnly: true
      volumes:
      - name: google-credentials-json-secret-volume
        secret:
          secretName: google-credentials-json-secret
