apiVersion: v1
kind: Service
metadata:
  name: login-register-backend-load-balancing
spec:
  selector:
    app: login-register-backend
  ports:
  - protocol: TCP
    port: 8001  # Port of this Load-Balancer Service
    targetPort: 8001 # Maps to the container's port
  type: LoadBalancer
  loadBalancerIP: 35.225.117.2  # login-register-backend-load-balancing-static-ip