# Generated by Django 5.0.6 on 2024-06-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_contactinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contactInfo',
            field=models.CharField(max_length=320, unique=True),
        ),
    ]
